development:
  adapter: mysql
  database: demoapp
  username: depot
  password: password1234
  host: 127.0.0.1
  
test:
  adapter: mysql
  database: demoapp
  username: depot
  password: password1234
  host: 127.0.0.1  
 