development:
 adapter: mysql2                                                                                                                                                                                  
 database: dempapp                                                                                                                                                                                  
  username: depot
  password: password1234                                                                                                                                                                              
 host: 127.0.0.1   